# Generated by Django 2.2.5 on 2021-12-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('음식명', models.CharField(max_length=20)),
                ('음식사진', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
