# Generated by Django 2.2.5 on 2021-12-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
    ]
