# Generated by Django 2.2.5 on 2021-12-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='음식사진',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
